name: Label Issues (Permissions Example)
on:
# excecuted when issue is opened
  issues:
    types:
      - opened
jobs:
  assign-label:
  # assigning permissions to jobs with permissions:
  # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  # can add permissions: to job level or entire workflow level, where they will apply to all jobs
  # permissions:  issues: is the one we need here . It can be read | write | none read-all write-all, etc...
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        # adds a label to the issue filed in github via the github api 
        run: |
          curl -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'content-type: application/json' \
          -d '{
              "labels": ["bug"]
            }' \
          --fail